# Form implementation generated from reading ui file '..\src\ui\home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons8-statistic-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 41);\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tab = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tab.setObjectName("tab")
        self.tab.setColumnCount(1)
        self.tab.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab.setHorizontalHeaderItem(0, item)
        self.gridLayout_3.addWidget(self.tab, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add.setStyleSheet("*{\n"
"    height: 25px;\n"
"    width: 150px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"*{\n"
"    background-color: rgba(30, 113, 14, 0.784);\n"
"}\n"
":hover{\n"
"    background-color: rgba(77, 160, 13, 0.874);\n"
"}")
        icon = QtGui.QIcon.fromTheme("add")
        self.btn_add.setIcon(icon)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_complete_tab = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_complete_tab.setStyleSheet("*{\n"
"    height: 25px;\n"
"    width: 150px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"*{\n"
"    background-color: rgba(28, 103, 143, 0.649);\n"
"\n"
"}\n"
"\n"
":hover{\n"
"    background-color: rgba(28, 112, 157, 0.81);\n"
"}")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.btn_complete_tab.setIcon(icon)
        self.btn_complete_tab.setObjectName("btn_complete_tab")
        self.horizontalLayout.addWidget(self.btn_complete_tab)
        self.btnDiagrammes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDiagrammes.setStyleSheet("*{\n"
"    height: 25px;\n"
"    width: 150px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"*{\n"
"    background-color: rgba(28, 103, 143, 0.649);\n"
"\n"
"}\n"
"\n"
":hover{\n"
"    background-color: rgba(28, 112, 157, 0.81);\n"
"}")
        self.btnDiagrammes.setObjectName("btnDiagrammes")
        self.horizontalLayout.addWidget(self.btnDiagrammes)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 22))
        self.menubar.setMinimumSize(QtCore.QSize(0, 0))
        self.menubar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("")
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menu_Fichier = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Fichier.setObjectName("menu_Fichier")
        self.menu_Edition = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Edition.setObjectName("menu_Edition")
        self.menuDiagrammes = QtWidgets.QMenu(parent=self.menubar)
        self.menuDiagrammes.setObjectName("menuDiagrammes")
        self.menuLin_aire = QtWidgets.QMenu(parent=self.menuDiagrammes)
        self.menuLin_aire.setObjectName("menuLin_aire")
        self.menu_Aide = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Aide.setObjectName("menu_Aide")
        self.menuTableau = QtWidgets.QMenu(parent=self.menubar)
        self.menuTableau.setObjectName("menuTableau")
        self.menu_Personnalisation = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Personnalisation.setObjectName("menu_Personnalisation")
        self.menu_Theme = QtWidgets.QMenu(parent=self.menu_Personnalisation)
        self.menu_Theme.setObjectName("menu_Theme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(parent=MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.moyenneArithmetiqueLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.moyenneArithmetiqueLabel.setObjectName("moyenneArithmetiqueLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.moyenneArithmetiqueLabel)
        self.moyenneGOmTriqueLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.moyenneGOmTriqueLabel.setObjectName("moyenneGOmTriqueLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.moyenneGOmTriqueLabel)
        self.moyenneGOmTriqueDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.moyenneGOmTriqueDoubleSpinBox.setMaximum(99999999.99)
        self.moyenneGOmTriqueDoubleSpinBox.setObjectName("moyenneGOmTriqueDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.moyenneGOmTriqueDoubleSpinBox)
        self.moyenne_artihmetique_double_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.moyenne_artihmetique_double_spin.setMaximum(99999999.99)
        self.moyenne_artihmetique_double_spin.setObjectName("moyenne_artihmetique_double_spin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.moyenne_artihmetique_double_spin)
        self.tauxDeVariationLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.tauxDeVariationLabel.setObjectName("tauxDeVariationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tauxDeVariationLabel)
        self.tauxDeVariationDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.tauxDeVariationDoubleSpinBox.setMaximum(999999.99)
        self.tauxDeVariationDoubleSpinBox.setObjectName("tauxDeVariationDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tauxDeVariationDoubleSpinBox)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.btn_calcul_params = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.btn_calcul_params.setStyleSheet("*{\n"
"    height: 25px;\n"
"    width: 150px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"*{\n"
"    background-color: rgba(28, 103, 143, 0.649);\n"
"\n"
"}\n"
"\n"
":hover{\n"
"    background-color: rgba(28, 112, 157, 0.81);\n"
"}")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.btn_calcul_params.setIcon(icon)
        self.btn_calcul_params.setObjectName("btn_calcul_params")
        self.gridLayout.addWidget(self.btn_calcul_params, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionNouveau = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNouveau.setIcon(icon)
        self.actionNouveau.setObjectName("actionNouveau")
        self.action_Ouvrir = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.action_Ouvrir.setIcon(icon)
        self.action_Ouvrir.setObjectName("action_Ouvrir")
        self.action_Enregistrer = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.action_Enregistrer.setIcon(icon)
        self.action_Enregistrer.setObjectName("action_Enregistrer")
        self.actionQuitter = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuitter.setIcon(icon)
        self.actionQuitter.setObjectName("actionQuitter")
        self.action_Reinitialiser_les_donn_es = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.action_Reinitialiser_les_donn_es.setIcon(icon)
        self.action_Reinitialiser_les_donn_es.setObjectName("action_Reinitialiser_les_donn_es")
        self.actionA_prop_os = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionA_prop_os.setIcon(icon)
        self.actionA_prop_os.setObjectName("actionA_prop_os")
        self.actionEnregistrer_sous = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionEnregistrer_sous.setIcon(icon)
        self.actionEnregistrer_sous.setObjectName("actionEnregistrer_sous")
        self.actionEffectifs = QtGui.QAction(parent=MainWindow)
        self.actionEffectifs.setObjectName("actionEffectifs")
        self.actionF_quences = QtGui.QAction(parent=MainWindow)
        self.actionF_quences.setObjectName("actionF_quences")
        self.actionDensit = QtGui.QAction(parent=MainWindow)
        self.actionDensit.setEnabled(False)
        self.actionDensit.setObjectName("actionDensit")
        self.actionAmplitude = QtGui.QAction(parent=MainWindow)
        self.actionAmplitude.setObjectName("actionAmplitude")
        self.actionCentre = QtGui.QAction(parent=MainWindow)
        self.actionCentre.setObjectName("actionCentre")
        self.actionBandes = QtGui.QAction(parent=MainWindow)
        self.actionBandes.setObjectName("actionBandes")
        self.actionCamamberg = QtGui.QAction(parent=MainWindow)
        self.actionCamamberg.setObjectName("actionCamamberg")
        self.actionVos_avis = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("face-cool")
        self.actionVos_avis.setIcon(icon)
        self.actionVos_avis.setObjectName("actionVos_avis")
        self.actionNuage_de_points = QtGui.QAction(parent=MainWindow)
        self.actionNuage_de_points.setObjectName("actionNuage_de_points")
        self.actionTrac = QtGui.QAction(parent=MainWindow)
        self.actionTrac.setObjectName("actionTrac")
        self.actionCourb = QtGui.QAction(parent=MainWindow)
        self.actionCourb.setObjectName("actionCourb")
        self.action_Clair = QtGui.QAction(parent=MainWindow)
        self.action_Clair.setObjectName("action_Clair")
        self.action_Sombre = QtGui.QAction(parent=MainWindow)
        self.action_Sombre.setObjectName("action_Sombre")
        self.actionCouleurs_de_lignes = QtGui.QAction(parent=MainWindow)
        self.actionCouleurs_de_lignes.setCheckable(True)
        self.actionCouleurs_de_lignes.setObjectName("actionCouleurs_de_lignes")
        self.menu_Fichier.addAction(self.actionNouveau)
        self.menu_Fichier.addAction(self.action_Ouvrir)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.action_Enregistrer)
        self.menu_Fichier.addAction(self.actionEnregistrer_sous)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionQuitter)
        self.menu_Edition.addAction(self.action_Reinitialiser_les_donn_es)
        self.menuLin_aire.addAction(self.actionTrac)
        self.menuLin_aire.addAction(self.actionCourb)
        self.menuDiagrammes.addAction(self.actionBandes)
        self.menuDiagrammes.addAction(self.menuLin_aire.menuAction())
        self.menuDiagrammes.addAction(self.actionCamamberg)
        self.menuDiagrammes.addAction(self.actionNuage_de_points)
        self.menu_Aide.addAction(self.actionVos_avis)
        self.menu_Aide.addSeparator()
        self.menu_Aide.addAction(self.actionA_prop_os)
        self.menuTableau.addAction(self.actionEffectifs)
        self.menuTableau.addAction(self.actionF_quences)
        self.menuTableau.addSeparator()
        self.menuTableau.addAction(self.actionCentre)
        self.menuTableau.addAction(self.actionAmplitude)
        self.menuTableau.addAction(self.actionDensit)
        self.menu_Theme.addAction(self.action_Clair)
        self.menu_Theme.addAction(self.action_Sombre)
        self.menu_Personnalisation.addAction(self.menu_Theme.menuAction())
        self.menu_Personnalisation.addAction(self.actionCouleurs_de_lignes)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menu_Edition.menuAction())
        self.menubar.addAction(self.menuTableau.menuAction())
        self.menubar.addAction(self.menuDiagrammes.menuAction())
        self.menubar.addAction(self.menu_Personnalisation.menuAction())
        self.menubar.addAction(self.menu_Aide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lantistick"))
        self.tab.setSortingEnabled(False)
        item = self.tab.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tab.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Modaltés (Xi)"))
        self.btn_add.setText(_translate("MainWindow", "Ajouter une ligne"))
        self.btn_complete_tab.setText(_translate("MainWindow", "Completer le tableau"))
        self.btnDiagrammes.setText(_translate("MainWindow", "Voir les diagrammes"))
        self.menu_Fichier.setTitle(_translate("MainWindow", "&Fichier"))
        self.menu_Edition.setTitle(_translate("MainWindow", "&Edition"))
        self.menuDiagrammes.setTitle(_translate("MainWindow", "&Diagrammes"))
        self.menuLin_aire.setTitle(_translate("MainWindow", "Linéaire"))
        self.menu_Aide.setTitle(_translate("MainWindow", "&Aide"))
        self.menuTableau.setTitle(_translate("MainWindow", "&Tableau"))
        self.menu_Personnalisation.setTitle(_translate("MainWindow", "&Personnalisation"))
        self.menu_Theme.setTitle(_translate("MainWindow", "&Theme"))
        self.groupBox.setTitle(_translate("MainWindow", "Parametres"))
        self.moyenneArithmetiqueLabel.setText(_translate("MainWindow", "Moyenne arithmetique : "))
        self.moyenneGOmTriqueLabel.setText(_translate("MainWindow", "Moyenne géométrique : "))
        self.tauxDeVariationLabel.setText(_translate("MainWindow", "Taux de variation : "))
        self.btn_calcul_params.setText(_translate("MainWindow", "Calculer"))
        self.actionNouveau.setText(_translate("MainWindow", "&Nouveau"))
        self.actionNouveau.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_Ouvrir.setText(_translate("MainWindow", "&Ouvrir"))
        self.action_Ouvrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Enregistrer.setText(_translate("MainWindow", "&Enregistrer"))
        self.action_Enregistrer.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionQuitter.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Reinitialiser_les_donn_es.setText(_translate("MainWindow", "&Reinitialiser les données"))
        self.actionA_prop_os.setText(_translate("MainWindow", "A prop&os"))
        self.actionEnregistrer_sous.setText(_translate("MainWindow", "Enregistrer-&sous"))
        self.actionEffectifs.setText(_translate("MainWindow", "Ajouter les éffectifs"))
        self.actionF_quences.setText(_translate("MainWindow", "Ajouter les fréquences"))
        self.actionDensit.setText(_translate("MainWindow", "Ajouter les densités"))
        self.actionAmplitude.setText(_translate("MainWindow", "Ajouter les amplitudes"))
        self.actionCentre.setText(_translate("MainWindow", "Ajouter les centres"))
        self.actionBandes.setText(_translate("MainWindow", "Bandes"))
        self.actionCamamberg.setText(_translate("MainWindow", "Camamberg"))
        self.actionVos_avis.setText(_translate("MainWindow", "Vos avis"))
        self.actionNuage_de_points.setText(_translate("MainWindow", "Nuage de points"))
        self.actionTrac.setText(_translate("MainWindow", "Tracé"))
        self.actionCourb.setText(_translate("MainWindow", "Courbé"))
        self.action_Clair.setText(_translate("MainWindow", "&Clair"))
        self.action_Sombre.setText(_translate("MainWindow", "&Sombre"))
        self.actionCouleurs_de_lignes.setText(_translate("MainWindow", "Couleurs de lignes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
